slice_name: hourly_efficiency_green
description: null
certified_by: null
certification_details: null
viz_type: heatmap
params:
  datasource: 1__table
  viz_type: heatmap
  slice_id: 2
  all_columns_x: hour_formatted
  all_columns_y: day_name
  metric:
    aggregate: AVG
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: avg_profit
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 4
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: FLOAT64
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: AVG(avg_profit)
    optionName: metric_nlewcsizwnr_6lrrzvfdwjt
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    comparator: Green
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_u9deupdrulp_7owtuiqhtzx
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: taxi_type
  row_limit: 10000
  linear_color_scheme: schemeRdBu
  xscale_interval: 1
  yscale_interval: 1
  canvas_image_rendering: pixelated
  normalize_across: heatmap
  left_margin: auto
  bottom_margin: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  time_format: '%d/%m/%Y'
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  show_legend: true
  show_perc: true
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"taxi_type","op":"==","val":"Green"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_profit","description":null,"expression":null,"filterable":true,"groupby":true,"id":4,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT64","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg_profit)","optionName":"metric_nlewcsizwnr_6lrrzvfdwjt","sqlExpression":null}],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"1__table","viz_type":"heatmap","slice_id":2,"all_columns_x":"hour_formatted","all_columns_y":"day_name","metric":{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"avg_profit","description":null,"expression":null,"filterable":true,"groupby":true,"id":4,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"FLOAT64","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"AVG(avg_profit)","optionName":"metric_nlewcsizwnr_6lrrzvfdwjt","sqlExpression":null},"adhoc_filters":[{"clause":"WHERE","comparator":"Green","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_u9deupdrulp_7owtuiqhtzx","isExtra":false,"isNew":false,"operator":"==","operatorId":"EQUALS","sqlExpression":null,"subject":"taxi_type"}],"row_limit":10000,"linear_color_scheme":"schemeRdBu","xscale_interval":1,"yscale_interval":1,"canvas_image_rendering":"pixelated","normalize_across":"heatmap","left_margin":"auto","bottom_margin":"auto","y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","time_format":"%d/%m/%Y","sort_x_axis":"alpha_asc","sort_y_axis":"alpha_asc","show_legend":true,"show_perc":true,"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: aa937c4a-0e25-4377-adb8-5dca8fe2f5e4
version: 1.0.0
dataset_uuid: f4152e1d-473e-4ccd-b0b4-09ae23845944
